ne smotri etot commit, ya chisto dla togo chob na nout perenesti
KillerSanss/EduHub.Learn pull request #3
Opened 2024-03-12 19:29 UTC by KillerSanss

2024-03-15 13:40 UTC, 1nsanov commented
1. Пояснительная бригада за реализацию обобщенных ошибок. (Зачем интерфейсы, зачем out, папка для ошибок уже есть в domain, почему решил создать новую в Application слое)
2. Иерархия недоделанная, почему интерфейсы сервисов лежат не папке, зато интерфейсы репозиториев лежат в отдельной папке?
3. Async пишут в конце, а не в начале названия метода
4. Почему не используем CancellationToken для асинхронных методов?
5. Почему в сервисах решил возвращать коллекцию типа List<T>, а например не IList<T> или Массив?
6. Student в названии лишнее, это относится ко всем подобным места (то есть во всех сервисах и репах) В твоей реализации слово Student уже есть в названии интерфейса (класса)
7. Не вижу конфигураций для AutoMapper
8. Все комментарии от CourseService относятся ко всем твои сервисам, с репозиториями похожая история
9. Для DTO можно использовать record’ы вместо классов
10. Документация энама Gender
11. Расположение свойств и конструкторов в домен сущностях

2024-03-15 13:41 UTC, 1nsanov requested changes

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/ICourseRepository.cs
> +    Task<Course> DeleteCourse(Guid courseId);
Зачем при удалении домен сущности в репозитории возвращать удаленную же сущность, её же не существует. Уверен, что удаления сущности хватит Guid?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/ICourseRepository.cs
> +public interface ICourseRepository
У тебя 4 интерфейса репозитория по сути делают одно и то же над доменными сущностями, как можно избежать такого дублирования похожего кода? Также нет документации методов. И асинхронные методы должны помечаться Async в конце названия

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEducatorRepository.cs
> +public interface IEducatorRepository
Не полная документация, не хватает Async в методах

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEnrollmentRepository.cs
> +public interface IEnrollmentRepository
Не полная документация, не хватает Async в методах

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEnrollmentRepository.cs
> +    Task<Enrollment> EnrollStudent(Guid studentId, Guid courseId, DateTime startDate);
Че за метод?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IStudentRepository.cs
> +public interface IStudentRepository
Не полная документация, не хватает Async в методах

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/ICourseService.cs
> +public interface ICourseService
Не хватает документации

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IEducatorService.cs
> +public interface IEducatorService
Не хватает документации

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IEnrollmentService.cs
> +public interface IEnrollmentService
Не хватает документации

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IStudentService.cs
> +public interface IStudentService
Не хватает документации

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/ICourseService.cs
> +    Task<CourseDto> AsyncAddCourse(CourseDto courseDto);
Async пишут в конце, а не в начале названия метода

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IEnrollmentService.cs
> +    Task<EnrollmentDto> AsyncEnrollStudent(Guid studentId, Guid courseId, DateTime startDate);
Как я понимаю, это метод зачисления студента на курс. Название не подходит, эти параметры лушче объеденить в Дто

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IStudentService.cs
> +    Task<StudentDto> AsyncAddStudent(StudentDto studentDto);
Student в названии лишнее, это относится ко всем подобным места (то есть во всех сервисах и репах) В твоем реализации слово Student уже есть в названии интерфейса (класса)

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        _mapper = mapper;
А что если от зависимости прилетит null?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +        _mapper = mapper;
А что если от зависимости прилетит null?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +        _mapper = mapper;
А что если от зависимости прилетит null?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        _mapper = mapper;
А что если от зависимости прилетит null?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +            throw new EntityConflictException<CourseDto>(courseDto, "Course is already exists");
Почему в дженерик типе пишешь дто, когда ошибка относится к доменным сущностям?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var existingCourse = await _courseRepository.GetCourseById(courseDto.Id);
А что будет, если courseDto прилетит null?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        await _courseRepository.AddCourse(newCourse);
Добавил новый курс, но а сохранить изменения в дб конексте не надо?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task<CourseDto> AsyncAddCourse(CourseDto courseDto)
Зачем нам в Дто поле Id при создании сущности?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        if (existingCourse != null)
Имеет ли смысл лезть в базу для проверки существующей записи по такому-то id, когда при сохранение сущности с дубликатом Id db context сам выплюнет ошибку?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var updatedCourse = _mapper.Map<Course>(courseDto);
А если дто будет null? Что будет, если по id в Дто не существует такого курса? Почему не используешь метод Update в Course?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        await _courseRepository.UpdateCourse(updatedCourse);
Где сохранение изменений?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var existingCourse = await _courseRepository.GetCourseById(courseId);
existingCourse - достаточно просто сourse.

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +            throw new EntityNotFoundException<Guid>(courseId, "Course does not exist");
Почему в дженерике тип Guid, когда исключение предназначено для доменных сущностей? Не хард кодим сообщения ошибок.

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var allCourses = await _courseRepository.GetAllCourses();
названием переменной сourses достаточно

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEducatorRepository.cs
> +    Task<Educator> DeleteEducator(Guid educatorId);
Уверен, что удаления сущности хватит Guid?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEnrollmentRepository.cs
> +    Task<Enrollment> DeleteEnrollment(Guid enrollmentId);
Уверен, что удаления сущности хватит Guid?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IStudentRepository.cs
> +    Task<Student> DeleteStudent(Guid studentId);
Уверен, что удаления сущности хватит Guid?

2024-03-15 13:41 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +            throw new EntityNotFoundException<Guid>(courseId, "Course does not exist");
Снова вопросы по использованию дженерик класса исключения

2024-03-20 15:05 UTC, 1nsanov commented
Почему BaseNotFoundException не абстрактный?

2024-03-20 15:08 UTC, 1nsanov commented
Зачем EnrollmentNotFoundException, EnrollmentConflictException , есть ли есть уже дженерик ошибка такого же плана?

2024-03-20 15:14 UTC, 1nsanov commented
Комменты в CourseService также касаются всех остальных сервисов

2024-03-20 23:15 UTC, KillerSanss commented
> Зачем EnrollmentNotFoundException, EnrollmentConflictException , есть ли есть уже дженерик ошибка такого же плана?

Хахаахахаха, этим исключениям уже столько лет, еще когда я domain исключения писал

2024-03-21 08:03 UTC, 1nsanov requested changes

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/CourseDto.cs
> +public record CourseDto(
Нет документации

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/EducatorDto.cs
> +public record EducatorDto(
Нет документации

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/EnrollmentDto.cs
> +public record EnrollmentDto(
Нет документации

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/StudentDto.cs
> +public record StudentDto(
Нет документации

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/EducatorDto.cs
> +    FullName FullName,
ValueObject не используем в ДТО

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/EducatorDto.cs
> +    Phone Phone,
ValueObject не используем в ДТО

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/StudentDto.cs
> +    FullName FullName,
ValueObject не используем в ДТО

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/StudentDto.cs
> +    Email Email,
ValueObject не используем в ДТО

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/StudentDto.cs
> +    FullAddress Address,
ValueObject не используем в ДТО

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/MappingConfiguration/СourseMapping.cs
> +public class СourseMapping : Profile
Подсказка в Rider

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEnrollmentRepository.cs
> +public interface IEnrollmentRepository
Почему нет наследования от базовой репы?

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IRepository.cs
> +public interface IRepository<TEntity>
Хорошо ли, что в качестве дженерика можно написать все что угодно?

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IRepository.cs
> +    Task<TEntity> GetByIdAsync(Guid id);
Где CancellationToken?

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IRepository.cs
> +    Task<TEntity> AddAsync(TEntity entity, CancellationToken token);
аргумент полонстью называем cancellationToken

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IRepository.cs
> +    Task<TEntity[]> GetAllAsync();
Потерял токен

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IRepository.cs
> +    Task<TEntity> UpdateAsync(TEntity entity, CancellationToken token);
нет  /// <param для CancellationToken

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/ICourseService.cs
> +    /// <param name="course">record Курса.</param>
Не рекорд курса, а Дто. Поправь во всех местах

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/IEnrollmentService.cs
> +    Task EnrollStudentAsync(EnrollmentDto enrollment, CancellationToken token);
Метод достаточно назвать AddAsync, из названия сервиса понятно, что добавление относится к сущности Enrollment

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/IEnrollmentService.cs
> +    Task<EnrollmentDto[]> GetStudentEnrollmentsAsync(Guid studentId);
Потерял токен отмены

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/IEnrollmentService.cs
> +    Task<EnrollmentDto[]> GetAllAsync();
Где токен отмены

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        _unitOfWork = unitOfWork;
Надо также проверять на null

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/MappingConfiguration/EducatorMapping.cs
> +namespace EduHub.StudentService.Application.Services.MappingConfiguration;
Название папки MappingConfiguration выглядит громоздким

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/MappingConfiguration/EducatorMapping.cs
> +public class EducatorMapping : Profile
В конце название лучше еще указывать ...Profile, относится ко всем классам производных от Profile

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var newCourse = _mapper.Map<Course>(course);
У тебя CourseDto имеет Id. Если я явно укажу Id в дто, то все равно на выходе получится другой id, так как в мапинге он создаст новый.

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task<CourseDto> AddAsync(CourseDto course, CancellationToken token)
Лучше назвать Дто аргументы с суффиксом Dto (courseDto), будет более читаемый код. Иначе можно подумать, что course это дб сущность, а не дто. Исправить во всех местах. И вместо newCourse, updatedCourse, deletedCourse и подобных случаях можно будет нывазать переменную course

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        return _mapper.Map<CourseDto>(newCourse);
У тебя нет конфига для обратного мапинга

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Domain/Eduhub.StudentService.Domain/Validations/Exceptions/EntityNotFoundException.cs
> +public class EntityNotFoundException<T> : BaseNotFoundException
Хорошо ли, что в дженерик тип можно написать любой тип?

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Domain/Eduhub.StudentService.Domain/Validations/Exceptions/EntityNotFoundException.cs
> +    public EntityNotFoundException(string paramName, string value)
Нет документация, и также нет у базового класса

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/UOW/IUnitOfWork.cs
> +    Task SaveChangesAsync(CancellationToken token);
Метод SaveChangesAsync в дб контексе возвращает не просто Task

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/UOW/IUnitOfWork.cs
> +public interface IUnitOfWork
Нет документации

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var updatedCourse = _mapper.Map<Course>(course);
При мапинге затрется Id из Дто в твоей реализации. Доходит дело до базы и валится ошибка

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        Guard.Against.Null(student, nameof(student));
Зачем nameof(student) ?

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/ICourseService.cs
> +    Task<CourseDto> GetAsync(Guid courseId);
Лучше назвать GetByIdAsync

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +        await _enrollmentRepository.EnrollStudentAsync(token);
Где SaveChanges?

2024-03-21 08:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/UOW/IUnitOfWork.cs
> +﻿namespace EduHub.StudentService.Application.Services.UOW;
На фоне всех остальных наименований название капсом UOW не смотрится

2024-03-21 12:43 UTC, 1nsanov requested changes
Думаю, что мешать исключения, которые используются и в слое Domain и в слое Application в одном месте (В Domain) не лучшее решение. То что относится к Application вынеси в слой Application, исключения которые используется только в Domain, пусть будут только в Domain

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EducatorProfile.cs
> +public class EducatorProfile : Profile
Почти, только Mapping надо было оставить. EducatorMappingProfile

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dto/CourseDto.cs
> +﻿namespace EduHub.StudentService.Application.Services.Dto;
Так как у тебя не одно дто, папку лучше назвать Dtos

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IEnrollmentRepository.cs
> +    Task AddAsync(CancellationToken cancellationToken);
А зачем?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IServices/IStudentService.cs
> +    Task<StudentDto> GetAsync(Guid studentId, CancellationToken cancellationToken);
Не совсем точное название метода

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/IServices/IEducatorService.cs
> +    Task<EducatorDto> GetAsync(Guid educatorId, CancellationToken cancellationToken);
Не совсем точное название метода

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        var course = _mapper.Map<Course>(courseDto);
Проблема с потерей Id так и осталась. Сейчас в передаваемой Дто и Id куда-то пропал

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Domain/Eduhub.StudentService.Domain/Validations/Exceptions/EntityNotFoundException.cs
> +public class EntityNotFoundException<T> : BaseNotFoundException where T : class
С таким ограничением я могу подставить любой ссылочный тип

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Repositories/IRepository.cs
> +public interface IRepository<TEntity> where TEntity : class
С таким ограничением я могу подставить любой ссылочный тип

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        return _mapper.Map<CourseDto>(course);
Теперь ты отдаешь Дто, у которой не Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        return _mapper.Map<CourseDto[]>(courses);
Теперь ты отдаешь Дто'шки, у которых нет Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        await _courseRepository.UpdateAsync(course, cancellationToken);
Можно не использовать метод Update от базы, у нас есть в сущностях методы Update

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +        var educator = _mapper.Map<Educator>(educatorDto);
Проблема с потерей Id так и осталась. Сейчас в передаваемой Дто и Id куда-то пропал

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +        await _educatorRepository.UpdateAsync(educator, cancellationToken);
Можно не использовать метод Update от базы, у нас есть в сущностях методы Update

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task<CourseDto> GetByIdAsync(Guid courseId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +            throw new EntityNotFoundException<Course>(nameof(courseId), courseId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task DeleteAsync(Guid courseId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +            throw new EntityNotFoundException<Course>(nameof(courseId), courseId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    public async Task<EducatorDto> GetAsync(Guid educatorId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +            throw new EntityNotFoundException<Course>(nameof(educatorId), educatorId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id. И почему в дженерике у тебя Course, когда работаем с Educator?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    public async Task DeleteAsync(Guid educatorId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +            throw new EntityNotFoundException<Course>(nameof(educatorId), educatorId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id. И почему в дженерике у тебя Course, когда работаем с Educator?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +            throw new EntityNotFoundException<Course>(nameof(enrollmentDto.StudentId), enrollmentDto.StudentId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id. И почему в дженерик типе Course, когда ошибка относится к студенту?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +            throw new EntityNotFoundException<Course>(nameof(enrollmentDto.CourseId), enrollmentDto.CourseId.ToString());
В nameof лучше всего прописывать свойства от класса, например Enrollment.CourseId.

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    public async Task AddAsync(EnrollmentDto enrollmentDto, CancellationToken cancellationToken)
Почему здесь решил не возвращать полную Дто после создания?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +        return _mapper.Map<EnrollmentDto[]>(enrollments);
Теперь ты отдаешь Дто'шки, у которых нет Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    public async Task DeleteAsync(Guid enrollmentId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +            throw new EntityNotFoundException<Course>(nameof(enrollment), enrollmentId.ToString());
В nameof лучше всего прописывать свойства от класса, например Enrollment.Id. И почему в дженерик типе Course, когда ошибка относится к зачислению?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +        return _mapper.Map<EducatorDto>(educator);
Теперь ты отдаешь Дто, у которой нет Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        var updatedStudent = _mapper.Map<Student>(studentDto);
Проблема с потерей Id так и осталась. Сейчас в передаваемой Дто и Id куда-то пропал. И можно обозовать просто student

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        await _studentRepository.UpdateAsync(updatedStudent, cancellationToken);
Можно не использовать метод Update от базы, у нас есть в сущностях методы Update

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    public async Task<StudentDto> GetAsync(Guid studentId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +            throw new EntityNotFoundException<Course>(nameof(studentId), studentId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id, и почему в дженерике Course, когда ошибка относится к студенту?

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        return _mapper.Map<StudentDto>(updatedStudent);
Теперь ты отдаешь Дто'шки, у которых нет Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        return _mapper.Map<StudentDto>(student);
Теперь ты отдаешь Дто'шки, у которых нет Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        return _mapper.Map<StudentDto[]>(students);
Теперь ты отдаешь Дто'шки, у которых нет Id

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    public async Task DeleteAsync(Guid studentId, CancellationToken cancellationToken)
В данном случае достаточно наименование агрумента "id"

2024-03-21 12:43 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +            throw new EntityNotFoundException<Course>(nameof(studentId), studentId.ToString());
В nameof лучше всего прописывать свойства от класса, например Course.Id, и почему в дженерике Course, когда ошибка относится к студенту?

2024-03-23 00:26 UTC, KillerSanss commented
> Думаю, что мешать исключения, которые используются и в слое Domain и в слое Application в одном месте (В Domain) не лучшее решение. То что относится к Application вынеси в слой Application, исключения которые используется только в Domain, пусть будут только в Domain

забыл про это когда комитил, сори, в некст исправлю

2024-03-25 08:50 UTC, 1nsanov requested changes
1. Напоминаю про папки с интерфейсами
2. Поправить наименование CourseMappingProfile
3. Поправить .csproj проекта с тестами
4. Беда с возвращаемыми Дто

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Interfaces/IRepositories/IEnrollmentRepository.cs
> +    Task<Enrollment> AddAsync(CancellationToken cancellationToken);
Не понимаю смысла этого метода, в базовой репе уже есть AddAsync. Здесь у тебя описан AddAsync, который просто принимает токен отмены

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dtos/Course/CourseDto.cs
> +public record CourseDto(
Где Id?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dtos/Educator/EducatorDto.cs
> +public record EducatorDto(
Где Id?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dtos/Enrollment/EnrollmentDto.cs
> +public record EnrollmentDto(
Где Id?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Dtos/Student/StudentDto.cs
> +public record StudentDto(
Где Id?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task<CreateCourseDto> AddAsync(CreateCourseDto courseDto, CancellationToken cancellationToken)
Почему возвращаем CreateCourseDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task<UpdateCourseDto> UpdateAsync(UpdateCourseDto courseDto, CancellationToken cancellationToken)
Почему возвращаем UpdateCourseDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    public async Task<CreateCourseDto[]> GetAllAsync(CancellationToken cancellationToken)
Почему возвращаем CreateCourseDto[]?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    public async Task<CreateEducatorDto> AddAsync(CreateEducatorDto educatorDto, CancellationToken cancellationToken)
Почему возвращаем CreateEducatorDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    public async Task<UpdateEducatorDto> UpdateAsync(UpdateEducatorDto educatorDto, CancellationToken cancellationToken)
Почему возвращаем UpdateEducatorDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    public async Task<CreateEducatorDto> GetByIdAsync(Guid id, CancellationToken cancellationToken)
Почему возвращаем CreateEducatorDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    public async Task<CreateEducatorDto[]> GetAllAsync(CancellationToken cancellationToken)
Почему возвращаем CreateEducatorDto[]?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    public async Task<CreateEnrollmentDto> AddAsync(CreateEnrollmentDto enrollmentDto, CancellationToken cancellationToken)
Почему возвращаем CreateEnrollmentDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    public async Task<CreateEnrollmentDto[]> GetAllAsync(CancellationToken cancellationToken)
Почему возвращаем CreateEnrollmentDto[]?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    public async Task<CreateEnrollmentDto[]> GetStudentEnrollmentsAsync(Guid studentId, CancellationToken cancellationToken)
Почему возвращаем CreateEnrollmentDto[]?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    public async Task<CreateStudentDto> AddAsync(CreateStudentDto studentDto, CancellationToken cancellationToken)
Почему возвращаем CreateStudentDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    public async Task<UpdateStudentDto> UpdateAsync(UpdateStudentDto studentDto, CancellationToken cancellationToken)
Почему возвращаем UpdateStudentDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    public async Task<CreateStudentDto> GetByIdAsync(Guid id, CancellationToken cancellationToken)
Почему возвращаем CreateStudentDto?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    public async Task<CreateStudentDto[]> GetAllAsync(CancellationToken cancellationToken)
Почему возвращаем CreateStudentDto[]?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        course.Update(courseDto.Name, courseDto.Description, courseDto.EducatorId);
Чтобы что-то обновить, надо бы удостовериться, что объект существует в бд и его модифицировать

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        }
Это часть кода уже дублируется в GetByIdAsync, можно ли сделать лучше?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +            new Phone(educatorDto.Phone));
Чтобы что-то обновить, надо бы удостовериться, что объект существует в бд и его модифицировать

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +        }
Это часть кода уже дублируется в GetByIdAsync, можно ли сделать лучше?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +            throw new EntityNotFoundException<Student>(nameof(CreateEnrollmentDto.StudentId), enrollmentDto.StudentId.ToString());
Логичней написать "nameof(**Enrollment**.StudentId)"

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +            throw new EntityNotFoundException<Course>(nameof(CreateEnrollmentDto.CourseId), enrollmentDto.CourseId.ToString());
Логичней написать "nameof(**Enrollment**.CourseId)"

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +        }
Это часть кода уже дублируется в AddAsync, можно ли сделать лучше?

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +            studentDto.Avatar);
Чтобы что-то обновить, надо бы удостовериться, что объект существует в бд и его модифицировать

2024-03-25 08:50 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        }
Это часть кода уже дублируется в GetByIdAsync, можно ли сделать лучше?

2024-03-25 17:10 UTC, KillerSanss commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Interfaces/IRepositories/IEnrollmentRepository.cs
> +    Task<Enrollment> AddAsync(CancellationToken cancellationToken);
Это зачисление студента на выбранный курс

2024-03-26 08:09 UTC, 1nsanov requested changes

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +        course.Update(courseDto.Name, courseDto.Description, courseDto.EducatorId);
Поправить логику Update дб модели

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/CourseService.cs
> +    private async Task<Course> ExistAsync(Guid id, CancellationToken cancellationToken)
Название метода не отражает его действия

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +        educator.Update(
Поправить логику Update дб модели

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EducatorService.cs
> +    private async Task<Educator> ExistAsync(Guid id, CancellationToken cancellationToken)
Название метода не отражает его действия

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    public async Task<CreateEnrollmentDto> AddAsync(CreateEnrollmentDto enrollmentDto, CancellationToken cancellationToken)
Все еще вовзращает не некорретную Дто

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +        await _enrollmentRepository.AddAsync(enrollmentDto.StudentId, enrollmentDto.CourseId, cancellationToken);
Метод Add репы должен принимать полную дб модель

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +    private async Task<Enrollment> ExistAsync(Guid id, CancellationToken cancellationToken)
Название метода не отражает его действия

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/EnrollmentService.cs
> +            throw new EntityNotFoundException<Educator>(nameof(Enrollment.Id), id.ToString());
В дженерике указан Educator, когда у тебя Enrollment

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +        student.Update(
Поправить логику Update дб модели

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +            throw new EntityNotFoundException<Educator>(nameof(Student.Id), id.ToString());
В дженерике Educator, когда у тебя Student

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Services/StudentService.cs
> +    private async Task<Student> ExistAsync(Guid id, CancellationToken cancellationToken)
Название метода не отражает его действия

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EducatorMappingProfile.cs
> +        CreateMap<EducatorDto, Educator>()
Нужен ди мапинг из Респонс Дто в Дб модель?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EducatorMappingProfile.cs
> +        CreateMap<Educator, CreateEducatorDto>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EducatorMappingProfile.cs
> +        CreateMap<Educator, UpdateEducatorDto>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EnrollmentMappingProfile.cs
> +        CreateMap<EnrollmentDto, Enrollment>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EnrollmentMappingProfile.cs
> +        CreateMap<Enrollment, CreateEnrollmentDto>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/StudentMappingProfile.cs
> +        CreateMap<StudentDto, Student>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/StudentMappingProfile.cs
> +        CreateMap<Student, CreateStudentDto>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/StudentMappingProfile.cs
> +        CreateMap<Student, UpdateStudentDto>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/СourseMappingProfile.cs
> +        CreateMap<CourseDto, Course>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/СourseMappingProfile.cs
> +        CreateMap<Course, CreateCourseDto>()
Нужен ли данный маппинг?

2024-03-26 08:09 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/СourseMappingProfile.cs
> +        CreateMap<Course, UpdateCourseDto>()
Нужен ли данный маппинг?

2024-03-26 11:34 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Interfaces/IRepositories/IEnrollmentRepository.cs
> +    Task<Enrollment> AddAsync(CancellationToken cancellationToken);
Добавление зачисления это и есть создание объекта, уже есть метод AddAsync в репе для этого

2024-04-01 12:03 UTC, 1nsanov requested changes

2024-04-01 12:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EducatorMappingProfile.cs
> +                Guid.NewGuid(),
Почему при мапинге UpdateDto в дб модель генерируется id?

2024-04-01 12:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/EducatorMappingProfile.cs
> +            .ForMember(d => d.Surname, o => o.MapFrom(e => e.FullName.Surname))
Такие длинные строки лучше переносить на новую (Например после запятой), по сокращениям лучше более понятней писать. Например, вместо d - dest, o - options. Поправить во всех местах

2024-04-01 12:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/StudentMappingProfile.cs
> +                Guid.NewGuid(),
Почему при мапинге UpdateDto в дб модель генерируется id?

2024-04-01 12:03 UTC, 1nsanov commented on src/Services/StudentService/Application/EduHub.StudentService.Application.Services/Mapping/СourseMappingProfile.cs
> +                Guid.NewGuid(),
Почему при мапинге UpdateDto в дб модель генерируется id?

2024-04-02 07:04 UTC, 1nsanov approved these changes

2024-04-02 07:19 UTC, merged