Api - Controllers
KillerSanss/EduHub.Learn pull request #6
Opened 2024-06-19 18:23 UTC by KillerSanss

2024-06-20 12:10 UTC, 1nsanov requested changes

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    private readonly CourseService _courseService;
Почему класс сервиса а не интерфейс?

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +        _courseService = courseService;
Не хватает проверки на null

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    public async Task<IActionResult> GetAllAsync(
надо явно указывать возвращаемый тип + использовать ActionResult<>

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    [HttpGet("get_by_id_course")]
Подумай над именами роутов, в инете есть стандарт по наименованием роутов по REST API

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +        return Ok(addedCourse);
При создании надо 201 возвращать

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +        switch (exception)
Конструкцию со switch можно написать короче

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +                httpStatusCode = HttpStatusCode.InternalServerError;
Не хватает обработки по NotFound и Conflict ошибкам

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Program.cs
> +builder.Services.AddAutoMapper(typeof(EnrollmentMappingProfile));
Можно регнуть кфг автомапера кароче через assembly

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Program.cs
> +Console.WriteLine(connectionString);
Зачем тебе тут CW ?

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Program.cs
> +app.UseMiddleware<MiddlewareExceptionHandler>();
Использование мидлвара ошибок должно быть самым первым, то есть сразу после var app = builder.Build();

2024-06-20 12:10 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Properties/launchSettings.json
> +  "iisSettings": {
Все настройки с iis можно удалить

2024-06-24 06:52 UTC, 1nsanov requested changes
1. Не вижу Fluent валидаций для Dto
2. Не вижу документации в свагере от summary комментариев
3. Для API еще необходимо создать докер-контейнер

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +[Route("[controller]")]
Имя роута должно начинаться с api, то есть должно быть "api/[Controller]".
Но [Controller] сделает нам наименование с большой буквы. Пусть в именах роутах не будет заглавных букв, разделение слов через '-' (Не через нижнее подчеркивание), ну и начинается с 'api'. Поправить во всех местах

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    [HttpGet]
Для списков лучше всего еще в роутах указывать множественное число, либо использовать слово 'list'

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    [HttpPut("{id:guid}")]
Для Put не используем id в роуте, он есть и так в body

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/EnrollmentController.cs
> +        [FromBody] CreateEnrollmentDto createEnrollmentDto,
В Dto есть Id, он не нужен при создании объекта

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Controllers/PingController.cs
> +    public IActionResult Pong()
Для этого метода не надо писать отдельный контроллер. Можно сделать через app.MapGet("api/ping", () => "pong"); после MapControllers()

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +                {
Поправить форматирование табуляции

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +                    EntityConflictException<BaseEntity> => HttpStatusCode.Conflict,
Лучше указывать базовые исключения

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/appsettings.json
> +    "AllowedHosts": "*",
Поправить форматирование табуляции в файле. + Не хватает апсетинга Development

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/Exception.cs
> +public class ExceptionResponse
Файл называется Exception, а класс ExceptionResponse. + Вынести в отдельную папку, например Models

2024-06-24 06:52 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Program.cs
> +builder.Services.AddAutoMapper(typeof(StudentMappingProfile).Assembly);
Не полная регистрации мапингов от автомапера

2024-06-24 07:00 UTC, 1nsanov requested changes

2024-06-24 07:00 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +            Message = exception.Message,
Желательно получать сообщения от исключения, включая её внутренние исключения

2024-06-24 07:00 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +            StackTrace = GetFullStackTrace(exception),
Метод немного не то возвращает по stack trace. У исключение есть поле .StackTrace

2024-06-24 13:05 UTC, 1nsanov requested changes

2024-06-24 13:05 UTC, 1nsanov commented on src/Services/StudentService/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +                    ValidationException => HttpStatusCode.BadRequest,
После написания флуент валидации здесь надо исключение от нагет пакета FluentValidation, сейчас ValidationException идет от System.ComponentModel.DataAnnotations

2024-06-26 06:46 UTC, 1nsanov requested changes
- Перепроверить флуент валидаторы и доработать их
- Протестировать и добавить кастомные ошибки по необходимости
- Поправить роуты апи

2024-06-26 06:46 UTC, 1nsanov commented on docker-compose.yaml
> +            - "5120:80"
Не хватает порта для https. 80 это для http, есть еще 443 для https

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    [HttpGet("get-all/list")]
Достаточно просто list оставить

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Program.cs
> +builder.Services.AddScoped<StudentCreateDtoValidator>();
Правильная регистрации валидаторов: https://docs.fluentvalidation.net/en/latest/aspnet.html

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    private readonly CourseCreateDtoValidator _courseCreateDtoValidator;
А зачем для валидаторы выносить в приватные рил онли поля?

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Controllers/CourseController.cs
> +        await _courseCreateDtoValidator.ValidateAndThrowAsync(createCourseDto, cancellationToken);
Можно и без приватного поля, await new CourseCreateDtoValidator().ValidateAndThrowAsync(createCourseDto, cancellationToken);
А во вторых флуент валидацию (Раз решил в ручном режиме прописывать) засунуть в сервисы. И при такой реализации регистрировать валидаторы в Program не нужно

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Controllers/CourseController.cs
> +    [HttpPut("update")]
Не используй подобные обозначения для CRUD операций, для этого существуют типы HTTP методы (POST, PUT, DELETE и т.д)

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Middleware/MiddlewareExceptionHandler.cs
> +            StackTrace = exception.StackTrace,
Для StackTrace также нужен метод, который собирает всё из внутренних исключений

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Properties/launchSettings.json
> +            "applicationUrl": "https://localhost:443;http://localhost:5120",
порт 443 тут не используем, + он у меня не работает. Также порты здесь и в контейнере должны быть разные

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Course/CourseCreateDtoValidator.cs
> +            .NotEmpty()
Тут достаточно NotEmpty, он также проверяет на null

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Course/CourseCreateDtoValidator.cs
> +            .MinimumLength(2)
У нас вроде не было условия на минимум 2 символа в названии курса

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Course/CourseCreateDtoValidator.cs
> +        RuleFor(x => x.Description)
Description тут не обязательное поле

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Course/CourseCreateDtoValidator.cs
> +            .NotNull()
Guid не может быть null

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Educator/EducatorCreateDtoValidator.cs
> +            .Matches(RegexPatterns.LettersPattern);
Для таких проверок лучше всего написать кастомное сообщение ошибке

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Educator/EducatorCreateDtoValidator.cs
> +            .NotEmpty()
Еще не хватает проверок на длину строки

2024-06-26 06:46 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Validators/Educator/EducatorUpdateDtoValidator.cs
> +            .GreaterThan(-1);
Понятней будет GreaterThanOrEqual(0)

2024-06-26 17:16 UTC, KillerSanss commented on docker-compose.yaml
> +            - "5120:80"
Хз я такую херь, наверное с этим намутил, но ладно, оно вроде работает.

2024-06-27 11:55 UTC, 1nsanov requested changes

2024-06-27 11:55 UTC, 1nsanov commented on src/Services/StudentService/Api/EduHub.StudentService.Api/Controllers/CourseController.cs
> +        Guid id,
Для читаемости лучше добавить атрибут [FromRoute] для таких аргументов

2024-07-02 06:42 UTC, 1nsanov requested changes
Проверь зависимости через snitch

2024-07-02 06:42 UTC, 1nsanov commented on src/Services/StudentService/Domain/Eduhub.StudentService.Domain/Validations/ErrorMessage.cs
>      public const string InvalidData = "{0} is incorrect";
Нигде не используется

2024-07-02 06:42 UTC, 1nsanov commented on src/Services/StudentService/Domain/Eduhub.StudentService.Domain/Validations/ErrorMessage.cs
Файл и класс назвать во множ. числе

2024-07-02 18:41 UTC, merged